# Generated by Django 3.2.7 on 2021-09-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('image', models.ImageField(upload_to='image')),
                ('thumbnail', models.ImageField(upload_to='image')),
            ],
        ),
    ]
