# Generated by Django 3.2.7 on 2021-09-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='album',
            name='thumbnail',
            field=models.URLField(max_length=255),
        ),
    ]
