# Generated by Django 3.2.7 on 2021-09-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumapi', '0002_auto_20210929_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='album',
            name='thumbnail',
            field=models.ImageField(upload_to='image'),
        ),
    ]
